### ISSUE TITLE
Reject email by IP ?

### ISSUE THREAD

**Issue by daslicht** [vithalreddy/node-mailin#1]
Hi,
is it possible to reject emails by ip ?
~ Marc

**Comment by vithalreddy** [comment]
@daslicht, Yes You can.
`/* Access simplesmtp server instance. */
nodeMailin.on("authorizeUser", function(connection, username, password, done) {
  if (connection.remoteAddress != "192.168.0.34") {
    done(new Error("Unauthorized!"), false);
  }
});`

**Comment by daslicht** [comment]
so that way  we could craete a blacklist based on IP's and block someone how send spam ?

**Comment by vithalreddy** [comment]
As of Now, No But it can be done in "startMessage"  event by passing a callback, If You're Interested Feel free to submit pr with this feature, otherwise I will add as soon as I'm free from current work.

For Now, You Can Ignore  Ignore emails from block listed IP's in "message" event

`/* Event emitted after a message was received and parsed. */
nodeMailin.on("message", async (connection, data, content) => {
   //check for block listed ip in connection object
});`

**Comment by daslicht** [comment]
I just installed it on my rasberry pi to give it a try :) 
It woudl be awesome if we could just reject messages from spammers, and show them a big middle finger by returning 403. I want them to know that they are not welcome

**Comment by daslicht** [comment]
Just got this:
```
pi@raspberrypi:~ $ sudo npm install -g node-mailin
/usr/bin/nodeMailin -> /usr/lib/node_modules/node-mailin/run-cli.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/node-mailin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
```
is that a problem ?

**Comment by vithalreddy** [comment]
> I just installed it on my rasberry pi to give it a try :)
> It woudl be awesome if we could just reject messages from spammers, and show them a big middle finger by returning 403. I want them to know that they are not welcome

we will add this feature definitely. But Due to time issues, we are not able to do it now.

**Comment by vithalreddy** [comment]
> Just got this:
> 
> ```
> pi@raspberrypi:~ $ sudo npm install -g node-mailin
> /usr/bin/nodeMailin -> /usr/lib/node_modules/node-mailin/run-cli.js
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/node-mailin/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
> ```
> is that a problem ?

No

**Comment by daslicht** [comment]
when installin node-mailin globally i should be able to run this command :?

```
node-mailin --help
```

**Comment by daslicht** [comment]
when i run it locally i get:
```
pi@raspberrypi:~/node $ sudo node app.js
warn: Either spamassassin or spamc are not available. Spam score computation is disabled.
error: Error: listen EADDRINUSE: address already in use 0.0.0.0:25
    at Server.setupListenHandle [as _listen2] (net.js:1258:14)
    at listenInCluster (net.js:1306:12)
    at doListen (net.js:1445:7)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:779:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
undefined
pi@raspberrypi:~/node $
```
