### ISSUE TITLE
How it's going to be different from mailin?

### ISSUE THREAD

**Issue by gnanaprakash** [vithalreddy/node-mailin#12]
I dont see any difference from original https://github.com/Flolagale/mailin vs yours. Please let me more in details, as I'm interested in forking the original package for my own use

**Comment by BetaHuhn** [comment]
@gnanaprakash  The only major difference is that the original [maillin](https://github.com/Flolagale/mailin) is not being maintained anymore while this one is. Also [node-mailin](https://github.com/vithalreddy/node-mailin) doesn't support webhooks. It only parses incoming emails as json and checks the dkim, spf, spam score (using spamassassin) and tells you in which language the email is written. 
~ Maximilian
