### ISSUE TITLE
Async/Await and DKIM verification.

### ISSUE THREAD

**Issue by xJoeyv** [vithalreddy/node-mailin#13]
Hi,

I love this package it works simple and efficient. I just want to know how I can verify my DKIM (keypair)? Since I know in HARAKA you need to HARAKA wich key you use. Also I wonder if I can use this in async/await?

**Comment by vithalreddy** [comment]
`async await` is supported and dkim is handled by `https://www.npmjs.com/package/dkim` package.

**Comment by xJoeyv** [comment]
@vithalreddy Awesome that I can use `async/await`. About DKIM I have to give it a look, Im fairly new to this and and got introduced into mailing by my current job and Haraka where I needed to set my PK as part of the server configuration.

Thanks for your effective and lightweight package and fast reply.

**Comment by vithalreddy** [comment]
@xJoeyv it only supports basic `dkim` verification.
PK verification is not supported.
