### ISSUE TITLE
how is this any different from https://github.com/Flolagale/mailin

### ISSUE THREAD

**Issue by jiangts** [vithalreddy/node-mailin#7]
https://github.com/Flolagale/mailin looks like basically the same library...

**Comment by vithalreddy** [comment]
It's same, but that lib is not maintained anymore.
We needed to use this in our product, so we are maintaining it.

**Comment by jiangts** [comment]
ok. Is there a `CHANGELOG.md` where we can see what patches are made? As it is, that one has way more stars / forks so I'm planning on using that one.

**Comment by iamchathu** [comment]
@jiangts Are you still maintains this? Is there any log for the changes you have made to Flolagale/mailin ?

**Comment by vithalreddy** [comment]
@iamchathu we are using it in our production server, working quite well, Hence we will be Maintaining it.
