### ISSUE TITLE
Missing fields in the mailinMsg received in the "message" event

### ISSUE THREAD

**Issue by Ibrahimtrrc** [vithalreddy/node-mailin#8]
hi,
i'm upgrading the package passing from [mailin ](https://www.npmjs.com/package/mailin) to "node-mailin" but a lot of things changed like the structure of the mailinmsg for instance. 

Can you provide an exemple of what we expect as a mailingMsg in this version please ?

For example i'm looking for the priority that was in the "old" mailinMsg 

````json
{
  "mailinMsg":
  {
     ...
      "priority": "normal", // I need this but can"t find it in data
     ...
}
````

Best regards,

**Comment by shifubrams** [comment]
so you close the issue without giving answers ?

**Comment by vithalreddy** [comment]
It's not implemented in this lib.
