### ISSUE TITLE
How to reject an incoming email?

### ISSUE THREAD

**Issue by BetaHuhn** [vithalreddy/node-mailin#9]
Is there a way to reject an incoming email? 
For example if someone sends an email to the server you could check if it was send to foo@bar.com and if not, you could send an error like the one outlook sends if an email adress doesn't exist (550 5.1.10 RESOLVER.ADR.RecipientNotFound;)
~ Maxi

**Comment by vithalreddy** [comment]
as of now, there is no api to reject email based on custom logic,
But you could do something like this,

`nodeMailin.on("message", function(connection, data, content) {
  console.log(data);
  // process or ignore if email is not found in your db
});`

**Comment by BetaHuhn** [comment]
I got it to work by changing the function onRcptTo() in the node-mailin.js from this
https://github.com/vithalreddy/node-mailin/blob/3ecc5bd659a320f696d5cf35c7ceeead159f5f55/lib/node-mailin.js#L470-L478

to only this:
```JavaScript
function onRcptTo(address, session, streamCallback) {
        _this.emit("validateRecipient", session, address.address, streamCallback)
}
```

Then you can use this listener
```JavaScript
nodeMailin.on('validateRecipient', async function(session, address, callback) {
   if(address == 'foo@bar.com'){
        callback();
    }else{
        callback(
           new Error("email adress not found on server")
         );
    }
});
```
to check if the recipient is valid and if not the email gets rejected instead of just not processed further
